# Common

debug: false

# Spring Framework

spring:
  profiles:
    active: default
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0